#!/bin/sh

# PROVIDE: ftp_watchd
# REQUIRE: NETWORKING SERVERS pure-ftpd
# KEYWORD: shutdown

. /etc/rc.subr

name=ftp_watchd
rcvar=ftp_watchd_enable

load_rc_config $name

command=/usr/local/sbin/pure-uploadscript
pidfile_ftp_watchd=${pidfile_ftp_watchd:-"/var/run/pure-uploadscript.pid"}
uploadscript=${uploadscript:-"/home/ftp/uploadscript"}
command_args="-B -p ${pidfile_ftp_watchd} -r ${uploadscript}"
ftp_watchd_enable=${ftp_watchd_enable:-"no"}
ftp_watchd_command=${ftp_watchd_command:-"echo 'Hi' >> /tmp/hi"}

echo "#!/bin/sh" > ${uploadscript}
echo "${ftp_watchd_command}" >> ${uploadscript}

run_rc_command "$1"
